#!/usr/bin/env perl

use warnings;
use strict;
use 5.01;
use open qw(:encoding(utf8) :std);
use TAP::Harness;

my $h=TAP::Harness
  ->new({verbosity => 1,
	lib       => [qw[lib]],
	color     => 1,
       });

$h->runtests(<t/*.t>);

